### ISSUE TITLE
Unable to decrypt after HDD crash and rebuild

### ISSUE THREAD

**Issue by mho-games** [Crypto-Notepad/Crypto-Notepad#20]
Hello, !
I can not access my notes after Windows Ver Change.

Old (setup) 
Synology NAS stores Note Files
DesktopPC  HDD Win7 64Bit with on 
Hardware Raid10 NFTS files system 
Win7-64 Bit 

New (setup)
Synology NAS stores Note Files (files not moved or changed at all) 
Desktop PC HDD Win 2008R2 (as Desktop OS not as server)
Same Hardware Raid Raid10 NFTS File system. 

My Computer crashed and burned and i need to replace 1 of my drive in Desktop PC
I replaced and rebuilt Raid and added a 500G SSD boot Drive. and rebuilt the 25Tb of RAID.
I install different version of windows. 2008R2 64Bit.
Just to be safe I installed all of my applications over again one by one. 
Crypto note being one of them... 

Problem Today 
Crypto can not access any of my notes ( NONE ). It just kicks it back as Bad Key. 
to double check myself and Keys (i am getting old) 
I opened a VMware previous snapshot of my Win7 system  and connected to the NAS.
The Snapshot could open the old Cnotes 
The New OS still can not.  

I was lucky that I had a snapshot. Or I would have been hosed. with 1500+ of these single page txt files. (Client Records.) Non-Profit Law Office

**Comment by Sigmanor** [comment]
@mho-games Well... I can't catch this bug. I try decrypt my notes on windows 7 and another version of windows 10, and I didn't have any problems. 

I can make debug version of Crypto Notepad, that will log all errors to txt file, and if you want, I send you this version, and you can try decrypt your files, and then you can send me this debug txt file, and I will try to figure out what's going on there.

**Comment by Sigmanor** [comment]
Issue closed due to lack of additional information. If necessary, add more information about the issue, and reopen it.
