### ISSUE TITLE
autoupdate last version

### ISSUE THREAD

**Issue by tsis2k** [Crypto-Notepad/Crypto-Notepad#21]
**Describe the bug**
hello
after launching the last update does not open the file saying that the password is incorrect, the password if it is the correct insurance. It has been right after the update.

**To Reproduce**
not posible open the notepad file

**Expected behavior**
hello
after launching the last update does not open the file saying that the password is incorrect, the password if it is the correct insurance. It has been right after the update

**Screenshots**

**Software version (please complete the following information):**
 - OS versionWindows 7
 - App version [e.g. v1.4.4]

**Additional context**

**Comment by Sigmanor** [comment]
@tsis2k Hi. I just checked your issue. 

Downloaded few old versions of the program, encrypt file with it, and decrypt it without any problems in the latest version. So I think you change some setting in "Encryption" tab or something, I don't think I can help you with this issue, sorry.

**Comment by Sigmanor** [comment]
Closed because not relevant.
