### ISSUE TITLE
Tool Bar Icons

### ISSUE THREAD

**Issue by smaragdus** [Crypto-Notepad/Crypto-Notepad#34]
Hello,

First, I would like to thank you for maintaining and improving Crypto Notepad, I appreciate your work.

There is just one, cosmetic, insignificant thing (introduced in version [1.4.0](https://github.com/Crypto-Notepad/Crypto-Notepad/releases/tag/v1.4.0)) that I do not like- from [Release-Notes](https://github.com/Crypto-Notepad/Crypto-Notepad/wiki/Release-Notes#v140-2019-01-08):

> New icons (http://p.yusukekamiyamane.com/)

I prefer the old tool bar icons (till version [1.3.0](https://github.com/Crypto-Notepad/Crypto-Notepad/releases/tag/v1.3.0)), screen:

![Crypto Notepad 1 3 0 - 2019-09-30 - toolbar - 002](https://user-images.githubusercontent.com/9025757/65916042-567fbb80-e3dd-11e9-8269-cb2e3358ea42.png)

to the new tool bar icons (from version [1.4.0](https://github.com/Crypto-Notepad/Crypto-Notepad/releases/tag/v1.4.0)), screen:

![Crypto Notepad 1 4 0 - 2019-09-30 - toolbar - 002](https://user-images.githubusercontent.com/9025757/65916198-98106680-e3dd-11e9-9322-0fbc4080d613.png)

Would it be too much of a trouble to provide an option to use the old tool bar icons?

Regards

**Comment by Sigmanor** [comment]
Hello,

Sad, I like new icons, but it will be easy to add option for enable old icons. I will add it to a new version :wink:

**Comment by smaragdus** [comment]
@Sigmanor 

Thank you very much for your quick response and for your kindness. If you prefer you may add the old icon set as a separate download.

I suppose that most people who use the program haven't even noticed the change. I find the old icons more homogeneous. Particularly I dislike new 'save' icon and new 'settings' icon. I suppose that I am maniacally obsessed with details so I would not be greatly disappointed if you have rejected my request.

Anyway, very few developers are as generous and helpful like you, especially when it comes to such whimsical demands like mine.

**BIG THANK YOU!**

**Comment by Sigmanor** [comment]
Done! I'm still testing new version, and I think I will release it within a month.

![](https://i.imgur.com/4qMkPCr.gif)

**Comment by smaragdus** [comment]
@Sigmanor 

Absolutely excellent, thank you!!!

It is nice that the tool bar icons loads dynamically and no restart is required.

By the way the vertical settings panel looks better, The status bar is also a nice addition.

I think I have a couple of ideas- shall I open new issues or post them here?

**Comment by Sigmanor** [comment]
Yes, feel free. You can open the new issue.

**Comment by Sigmanor** [comment]
Yes, feel free. You can open the new issue.

**Comment by Sigmanor** [comment]
@smaragdus 

Ok, i'll look at new issues

For now, there is no binaries for 1.6.0 I just testing new version. If you want, write me in telegram, I will send you binaries, and you can test new version before release.
