### ISSUE TITLE
Minimize to Tray [Feature request]

### ISSUE THREAD

**Issue by smaragdus** [Crypto-Notepad/Crypto-Notepad#35]
I would like to suggest a small enhancement which would be useful at least for me- and option to minimize [Crypto Notepad](https://crypto-notepad.info/) to system tray. Currently I use an external tool to achieve this- [SmartSystemMenu](https://github.com/AlexanderPro/SmartSystemMenu), which adds additional commands to title bar, screen:

![Crypto Notepad 1 5 1 - 2019-10-08 - 001](https://user-images.githubusercontent.com/9025757/66405979-91907900-e9f3-11e9-8960-8799568db3d5.png)

but native support for system tray would be better. Perhaps you may add a couple of new check boxes under **Tools - Settings - Application**:

- **Minimize to tray;**
- **Close to tray;**

When **Minimize to tray** is enabled the program goes to system tray on minimize.
When **Close to tray** is enabled the program goes to system tray on close.

If tray support is implemented you may add a couple of tray commands, right click on tray icon:

- **Show;**
- **Exit:**

If you don't find this feature request useful enough feel free to discard it, I use many programs and my task bar becomes easily cluttered so I prefer to send the programs which are not immediately needed to system tray. My preferred settings would be to minimize the program to task bar and to close it to system tray ( **Minimize to tray**  not checked, **Close to tray** checked).

**Comment by Sigmanor** [comment]
@smaragdus  Yes, nice idea! I think it's easy to implement. I can add some new checkboxes to settings.

**Comment by smaragdus** [comment]
@Sigmanor 

> I think it's easy to implement. I can add some new checkboxes to settings.

Thank you.

**Comment by Sigmanor** [comment]
@smaragdus icon in tray must be shown always, or when the app is minimized to tray?

**Comment by Sigmanor** [comment]
@smaragdus  also, how to combine this feature with the **Auto lock on minimize** function? Lock and minimize to tray? Or just disallow minimize to tray when  **Auto lock on minimize** function is enabled?

**Comment by smaragdus** [comment]
@Sigmanor 

> icon in tray must be shown always, or when the app is minimized to tray?

I suppose that if tray is not enabled the tray icon should not be shown, When tray is enabled- then better always show tray icon.

> also, how to combine this feature with the **Auto lock on minimize** function? Lock and minimize to tray? Or just disallow minimize to tray when **Auto lock on minimize** function is enabled?

What I think- if **Auto lock on minimize** is enabled it should always work no matter whether **Crypto Notepad** goes to task bar or to system tray- it is minimized and it does not matter whether it is minimized to system tray or to task bar. For me this would be logical. What do you think?

**Comment by smaragdus** [comment]
@Sigmanor 

Thank you.
