### ISSUE TITLE
Always on Top [Feature request]

### ISSUE THREAD

**Issue by smaragdus** [Crypto-Notepad/Crypto-Notepad#36]
You may consider adding a new command:

- **Always on Top** (or just **On Top**);

perhaps under **Edit** menu, **CTRL+T** keyboard shortcut seems logical.

I tried to use an external tool to achieve this ([SmartSystemMenu](https://github.com/AlexanderPro/SmartSystemMenu), which adds additional commands in the title bar), screen:

![Crypto Notepad 1 5 1 - 2019-10-08 - 003](https://user-images.githubusercontent.com/9025757/66409656-804a6b00-e9f9-11e9-8d8a-bce71194e064.png)

but it didn't work as expected because the main window is always on top of **Enter the encryption key** window and it is impossible to enter the encryption key. So if **Always on Top** is implemented then **Enter the encryption key** window should be on top of the main window.

**Always on Top** feature may facilitate the use of drag&drop. But if you think that this is a fancy feature which requires too much work feel free to close this issue.

**Comment by Sigmanor** [comment]
@smaragdus Nice. I will look what I can do.

Yo want control this feature in title bar context menu? Or in settings? Or with some hotkey?

**Comment by smaragdus** [comment]
@Sigmanor 

> You want control this feature in title bar context menu? Or in settings? Or with some hotkey?

Perhaps activation of 'Always on Top' via a hot key (for example 'CTRL+T') would be enough. There might be such 'Always on Top' under 'Edit' menu. Or perhaps a button in the tool bar. Or perhaps in settings. You choose. For me a hot key or a tool bar button will be enough.

**Comment by smaragdus** [comment]
@Sigmanor 

Thanks.
