### ISSUE TITLE
[Feature request] Tabs support

### ISSUE THREAD

**Issue by Sigmanor** [Crypto-Notepad/Crypto-Notepad#4]
Add tabs support, like in notepad++

**Comment by smaragdus** [comment]
@Sigmanor
This will be a nice feature, thank you.

**Comment by Sigmanor** [comment]
Found a ready solution: https://github.com/VPKSoft/ScintillaTabbedTextControl
May be implemented with #44

**Comment by Sigmanor** [comment]
#54
