### ISSUE TITLE
[Feature request] Auto lock the application based on time

### ISSUE THREAD

**Issue by petvo78** [Crypto-Notepad/Crypto-Notepad#48]
**Auto lock the application based on time**

In the setting add a "lock timeout". When the editor is out of focus longer than the time put in the setting, the application gets locked and needs the password or a pin to unlock again.

**Comment by Sigmanor** [comment]
@petvo78 You mean auto-lock file by timer only when app lose focus? Or even when app is in focus, but its not using.

**Comment by petvo78** [comment]
Hi, I would prefer "is not being used" if that is possible. Thanks!

**Comment by Sigmanor** [comment]
> Hi, I would prefer "is not being used" if that is possible. Thanks!

Yes it's possible, but it can take a time to do this. I already made test build with able to lock app when the window is inactive for some time, it's work fine, but I can't understand for what this function, if exist "auto lock on minimize", or you can just press "ctrl+l" to lock file.

**Comment by petvo78** [comment]
So maybe I am not so good at explaining my use case, but this is how I use it. I have a bunch of password that I store in the crypto-notepad. A couple times a day I launch the app and copy the passwords. Then I do not use it for a while (do not have the habit to ctrl+I ever time). I do a lot of presenations at work so sometimes the crypto-notepad is shown to all ;-) By simply locking it by inactivity would make it much more "safe" for me - always knowing that it is locked after, lets say, 5 minutes of non activity. Anyway thanks for responing to the request :)

**Comment by Sigmanor** [comment]
@petvo78 Ok now I'm more clear understand what you want :) It's sounds logical. 

For now I made it like this: when app window is inactive more than "minutes from settings", app is locking automatically.

I can add able auto lock app even if app window is active but not using more than "minutes from settings".

I will try add this feature after holidays.

**Comment by petvo78** [comment]
> @petvo78 Ok now I'm more clear understand what you want :) It's sounds logical.
> 
> For now I made it like this: when app window is inactive(not in focus) more than "minutes from settings", app is locking automatically.
> 
> I can add able auto lock app even if app window is active but not using more than "minutes from settings".
> 
> I will try add this feature after holidays.

great :) thanks

**Comment by Sigmanor** [comment]
So, I made bunch of tests,  made a few test builds, but still decide to make this feature like as I wrote earlier: when window is not in focus more then **minutes from settings**, app is locking automatically. 

Make auto lock app even if window in focus but not used is possible, but I need to track a lot of actions that the user can do with app, and for this I need to write a lot of code, and spend a lot of time, so I decide to make it like this. I'm planning release new version with adding this feature in the next week.

**Comment by petvo78** [comment]
> So, I made bunch of tests, made a few test builds, but still decide to make this feature like as I wrote earlier: when window is not in focus more then **minutes from settings**, app is locking automatically.
> 
> Make auto lock app even if window in focus but not used is possible, but I need to track a lot of actions that the user can do with app, and for this I need to write a lot of code, and spend a lot of time, so I decide to make it like this. I'm planning release new version with adding this feature in the next week.

ok, sounds like a good approach, thanks.

**Comment by Sigmanor** [comment]
This feature was added in the new release (v1.6.6). Now I'm closing this issue. If you find any bugs, please open a new issue.
