### ISSUE TITLE
Ctrl+Alt+S for Settings is "ś" in Polish

### ISSUE THREAD

**Issue by MrEljote** [Crypto-Notepad/Crypto-Notepad#49]
Ctrl+Alt+S launches settings, which prevents to type "ś" mapped to the same key. "Ś" is a special Polish character. 
I'd be glad if you could remap the "Settings" menu item to some other shortcut (please do not use Ctrl+Alt+Z,  ..X, ..A, ..L, ..O ..E ..C either :))

**Comment by Sigmanor** [comment]
Ok, I will change this keyboard shortcuts. 

Also, in the next release, you will able to completely disable keyboard shortcuts.

**Comment by Sigmanor** [comment]
Shortcut keys was remapped in the new release (v1.6.6). Now I'm closing this issue. If you find any bugs, please open a new issue.
