### ISSUE TITLE
program not starting

### ISSUE THREAD

**Issue by Ambaquista** [Crypto-Notepad/Crypto-Notepad#50]
After upppdatimg from v.: 1.5, I get this message (Win 10 v.:1909):
"
[Window Title]
c:\Utilities\Crypto Notepad.exe
[Content]
c:\Utilities\Crypto Notepad.exe
Operation did not complete successfully because the file contains a virus or potentially unwanted software.
[OK]
"
and the program didn´t work!
What is the problem?
b rgds

**Comment by Sigmanor** [comment]
This error not from app, it's from your antivirus app. So I can't fix it.

Seems crypto notepad detected as malware - https://www.virustotal.com/gui/file/ff18ffde2dd3092beb5e8b1df2bff9bdcadd6c43f98460c55715bf29cd84b657/summary
