### ISSUE TITLE
Cannot Build Solution [BUG]

### ISSUE THREAD

**Issue by pauljayd** [Crypto-Notepad/Crypto-Notepad#51]
Downloaded Crypto-Notepad version 1.6.7.0 on 8/19/20.
Downloaded Visual Studio Community 2019, downloaded Microsoft .NET Framework 4.6.1 Targeting Pack, Targeting Pack (ENU), and SDK.
Started "Build Solution", and received the following errors: 

    1>C:\Users\Paul\Downloads\Crypto-Notepad-master\Crypto Notepad\Forms\PasswordGeneratorFrom.cs(52,72,52,86): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

    1>C:\Users\Paul\Downloads\Crypto-Notepad-master\Crypto Notepad\Forms\PasswordGeneratorFrom.cs(56,23,61,71): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

Don't know what to do at this point.
 
**Expected behavior**
A successful Build.

**Software version (please complete the following information):**
 - OS version =  Windows 10

**Comment by Sigmanor** [comment]
Hi. 

I just downloaded Crypto-Notepad 1.6.7 to virtual machine with **Windows 10** and visual studio:
```
Microsoft Visual Studio Community 2019
Version 16.6.5
VisualStudio.16.Release/16.6.5+30320.27
Microsoft .NET Framework
Version 4.8.03752
```
![image](https://user-images.githubusercontent.com/7986067/90766076-a7e5b180-e2f3-11ea-8b79-379f1dadfa49.png)

And build was sucsefull:
```
1>------ Build started: Project: Crypto Notepad, Configuration: Debug Any CPU ------
1>  Crypto Notepad -> C:\Users\Sigmanor\source\repos\Crypto-Notepad\Crypto Notepad\bin\Debug\Crypto Notepad.exe
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

So I think you just missed to install some package while installing VS.

**Comment by pauljayd** [comment]
Yes, I un-installed / re-installed Visual, and everything is OK.
