### ISSUE TITLE
Removing the "Try to decrypt %filename% file?" Message

### ISSUE THREAD

**Issue by cwldev** [Crypto-Notepad/Crypto-Notepad#52]
Crypto-Notepad is such a great tool, but this one thing kind of drives me crazy.

I'm using version 1.6.7 on Windows 10

So, when opening a file by way of drag and drop, a Windows association or File -> Open, the message The "Try to decrypt %filename% file?" pops up requiring an answer. This requires an (often) needless click when I think this process could be done better.

How? Perhaps opening files with the TXT extension as unencrypted by default (and provide an option in the interface to decrypt), the inverse goes for files using CNP - assuming these are encrypted. 

It's possible it could be a program-wide option (Always assume TXT files are unencrypted), something like that.

To be able to open and close simple TXT files unimpeded (most often use case I'd imagine) and then offering the encrypted options when signalled, the program is far easier to use.

**Comment by Sigmanor** [comment]
Hi.

That's was make for people who don't use .cnp files to store encrypted information, and for more security, when possible hacker getting your files, he can't know what tool was used to encrypt file. 

Of course I can add an option like "Always assume TXT files are unencrypted", but I won't change this behaviour by default.

**Comment by Sigmanor** [comment]
I will able to release new version in the next month. If you want to test this feature earlier, text me in the [telegram ](https://t.me/Sigmanor) or [email](mailto:sigmanor@pm.me) me, and I will send you the executable.

**Comment by cwldev** [comment]
That's cool.. I'd love to see how things work out (and test it). We'll connect when you're there and hopefully I can do that. Thanks!

**Comment by Sigmanor** [comment]
Done. New version with this enhancement will be released in september.
