### ISSUE TITLE
release for linux os

### ISSUE THREAD

**Issue by mshamsi502** [Crypto-Notepad/Crypto-Notepad#55]
it's so good if released for Linux os

**Comment by Sigmanor** [comment]
Hi. According to [contribute ](https://github.com/Crypto-Notepad/Crypto-Notepad/blob/master/CONTRIBUTING.md#things-that-will-never-be-in-this-project) guide:  Crypto Notepad will be only for windows. Maybe sometime, but it will be as a completely new project.
