### ISSUE TITLE
[Feature request] support for NT 5.1

### ISSUE THREAD

**Issue by andika207** [Crypto-Notepad/Crypto-Notepad#62]
it's a shame it doesn't support Windows XP.

**Comment by Sigmanor** [comment]
It's a shame that someone still using Windows XP.

But if seriously,  app can't work on Windows XP, because some packages that use Crypto Notepad don't support Windows XP, and I don't want to spend time to fixing this for the old and unsupported OS.

**Comment by andika207** [comment]
one month later..... you have not fixed this issue yet.
you can make use of an older version of your compiling software utility so you can get support for XP

**Comment by andika207** [comment]
> It's a shame that someone still using Windows XP.

no it isn't. because there's no ''bloatware removal'' tool for WinXP 
moreover, your bad friend Vladimir Putin is still using WinXP 
personally I don't use any real time antivirus, proxy, VPN or whatever else and I do online shopping with no issues.
only an ignorant would ever think XP doesn't work because the lack of updates or that it's full of viruses.

cheers

**Comment by andika207** [comment]
> It's a shame that someone still using Windows XP.

no it isn't. there's no ''bloatware removal'' tool for WinXP for a good reason
moreover, your bad friend Vladimir Putin is still using WinXP 
personally I don't use any real time antivirus, proxy, VPN or whatever else and I do online shopping with no issues.
only an ignorant would ever think XP doesn't work because the lack of updates or that it's full of viruses.

cheers

**Comment by Sigmanor** [comment]
cheers
